version: 0.1

phases:
  install:
    commands:
      - echo installing nodejs...
  pre_build:
    commands:
      - echo installing dependencies...
  build:
    commands:
      # - echo testing...
      - echo building...
      #- ng build --prod
