version: 0.1

phases:
  install:
    commands:
      - apt update
      - apt install -y awscli
  pre_build:
    commands:
      - echo installing dependencies...
  build:
    commands:
      # - echo testing...
      - echo building...
  post_build:
    commands:
      - aws s3 cp ./* s3://amitech21/ --recursive --acl public-read-write
